import React, { FC } from 'react'
import { Api } from '@/ui/components/Api'

export const ButtonApi: FC = () => (
    <Api>
        <p>Different button styles can be generated by setting Button properties.
            The recommended order is:
            <code>type</code> {'->'}
            <code>shape</code> {'->'}
            <code>size</code> {'->'}
            <code>loading</code> {'->'}
            <code>disabled</code>.
        </p>
        <table>
            <thead>
            <tr>
                <th>Prop</th>
                <th>Description</th>
                <th>Type</th>
                <th>Default</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>block</td>
                <td>Option to fit button width to its parent width</td>
                <td>boolean</td>
                <td>false</td>
            </tr>
            <tr>
                <td>danger</td>
                <td>Set the danger status of button</td>
                <td>boolean</td>
                <td>false</td>
            </tr>
            <tr>
                <td>disabled</td>
                <td>Disabled state of button</td>
                <td>boolean</td>
                <td>false</td>
            </tr>
            <tr>
                <td>ghost</td>
                <td>Make background transparent and invert text and border colors</td>
                <td>boolean</td>
                <td>false</td>
            </tr>
            <tr>
                <td>href</td>
                <td>Redirect url of link button</td>
                <td>string</td>
                <td>-</td>
            </tr>
            <tr>
                <td>htmlType</td>
                <td>Set the original html <code>type</code> of <code>button</code></td>
                <td>string</td>
                <td><code>button</code></td>
            </tr>
            <tr>
                <td>icon</td>
                <td>Set the icon component of button</td>
                <td>ReactNode</td>
                <td>-</td>
            </tr>
            <tr>
                <td>loading</td>
                <td>Set the loading status of button</td>
                <td>boolean | {'{delay: number}'}</td>
                <td>false</td>
            </tr>
            <tr>
                <td>shape</td>
                <td>Can be set button shape</td>
                <td><code>default</code> | <code>circle</code> | <code>round</code></td>
                <td>'default'</td>
            </tr>
            <tr>
                <td>size</td>
                <td>Set the size of button</td>
                <td><code>large</code> | <code>middle</code> | <code>small</code></td>
                <td><code>middle</code></td>
            </tr>
            <tr>
                <td>target</td>
                <td>Same as target attribute of a, works when href is specified</td>
                <td>string</td>
                <td>-</td>
            </tr>
            <tr>
                <td>type</td>
                <td>Can be set to <code>primary</code> <code>ghost</code> <code>dashed</code> <code>link</code>
                    <code>text</code> <code>default</code></td>
                <td>string</td>
                <td><code>default</code></td>
            </tr>
            <tr>
                <td>onClick</td>
                <td>Set the handler to handle <code>click</code> event</td>
                <td>(event) =&gt; void</td>
                <td>-</td>
            </tr>
            </tbody>
        </table>
    </Api>
)
